apiVersion: v1
kind: Service
metadata:
  name: catsnap-reservation
  labels:
    app: catsnap-reservation
spec:
  type: ClusterIP
  selector:
    app: catsnap-reservation
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080