apiVersion: v1
kind: Service
metadata:
  name: catsnap-gateway
  labels:
    app: catsnap-gateway
spec:
  type: ClusterIP
  selector:
    app: catsnap-gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
