apiVersion: v1
kind: Service
metadata:
  name: catsnap-authorization
  labels:
    app: catsnap-authorization
spec:
  type: ClusterIP
  selector:
    app: catsnap-authorization
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080