name: Test Mono Module

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Start mongodb
        run: |
          docker run --name mongodb-test -d -p 27017:27017 mongo

          echo "Waiting for MongoDB to be ready..."
          for i in {1..10}; do
            if docker exec mongodb-test mongosh --eval "db.adminCommand('ping')" > /dev/null 2>&1; then
              echo "MongoDB is ready!"
              break
            fi
            echo "MongoDB not ready yet... retrying ($i)"
            sleep 5
          done

          echo 'mongosh catsnap_test' > init.js
          docker exec -i mongodb-test bash < init.js

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test mono module
        run: ./gradlew --info :mono:test

      - name: Publish test results for mono
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: 'mono/build/test-results/test/TEST-*.xml'
          check_name: Test Results (mono)

      - name: Publish test report for mono
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: 'mono/build/test-results/test/TEST-*.xml'
          check_name: Test Report (mono)